import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f4fbf6",
        "primary": "#002417",
        "on-secondary": "#ffffff",
        "tertiary-container": "#453000",
        "on-tertiary-fixed-variant": "#5d4200",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-secondary-container": "#636361",
        "on-primary-fixed-variant": "#234f3c",
        "tertiary-fixed-dim": "#f0bf5e",
        "error-container": "#ffdad6",
        "on-primary-container": "#79a68f",
        "on-surface-variant": "#414944",
        "on-surface": "#161d1a",
        "background": "#f4fbf6",
        "surface-container-highest": "#dde4df",
        "outline-variant": "#c0c8c2",
        "secondary": "#5e5e5c",
        "surface-container": "#e8f0ea",
        "secondary-fixed": "#e4e2df",
        "inverse-surface": "#2b322f",
        "outline": "#717973",
        "on-background": "#161d1a",
        "surface-tint": "#3c6753",
        "inverse-on-surface": "#ebf2ed",
        "primary-fixed": "#beedd4",
        "primary-fixed-dim": "#a2d1b9",
        "on-primary-fixed": "#002115",
        "surface-variant": "#dde4df",
        "surface-bright": "#f4fbf6",
        "on-secondary-fixed": "#1b1c1a",
        "surface-dim": "#d4dcd7",
        "on-secondary-fixed-variant": "#474745",
        "surface-container-low": "#eef5f0",
        "tertiary": "#2a1c00",
        "secondary-container": "#e1dfdc",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#c8c6c4",
        "surface-container-high": "#e3eae5",
        "primary-container": "#0d3b2a",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffdea5",
        "on-tertiary-container": "#c29538",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#261900",
        "inverse-primary": "#a2d1b9",
        "on-tertiary": "#ffffff",
      },
      fontFamily: {
        "display-lg": ["Geist", "sans-serif"],
        "display-lg-mobile": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "data-tabular": ["JetBrains Mono", "monospace"],
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "container-max": "1280px",
        "gutter": "24px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "unit": "4px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};
export default config;
